/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jesse.GA_ANN;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.concurrent.*;

/**
 *
 * @author xuhao
 */
public class EvolutionControl extends javax.swing.JFrame 
{

    /**
     * Creates new form EvolutionControl
     */
    public EvolutionControl()throws Exception 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setSize(new java.awt.Dimension(1920, 1080));
        jProgressBar1 = new javax.swing.JProgressBar();
        StartBut = new javax.swing.JButton();
        data_vis = new DataVis();
        popsize = new javax.swing.JTextField();
        PopSizeText = new javax.swing.JLabel();
        IterStepText = new javax.swing.JLabel();
        iterstep = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartBut.setLabel("开始");
        StartBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(data_vis);

        popsize.setText("01000");
        popsize.setName(""); // NOI18N
        popsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        PopSizeText.setText("种群数：");

        IterStepText.setText("时间");

        iterstep.setText("010");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PopSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(popsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(IterStepText)
                        .addGap(57, 57, 57)
                        .addComponent(iterstep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StartBut)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(data_vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(data_vis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartBut)
                    .addComponent(popsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopSizeText)
                    .addComponent(IterStepText)
                    .addComponent(iterstep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    class threads implements Runnable
    {
        int k;Evo_Mass best;
        int num,step;
        public void run() 
        {
            try {
                new GA_Ann_Mas(num,data_vis).DisplayDevelop(step);
            } catch (Exception ex) {
                Logger.getLogger(EvolutionControl.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        threads()
        {
            num=Integer.valueOf(popsize.getText()  ).intValue();
            step=Integer.valueOf(iterstep.getText() ).intValue();
            System.out.printf("Start Develop number: %d ,Step :%d ",num,step);
        }
    }
    private void StartButActionPerformed(java.awt.event.ActionEvent evt)
    {
        try{
        data_vis.clear();
        ExecutorService exe=Executors.newFixedThreadPool(1);
        exe.execute(new threads());
        }
        catch(Exception e)
        {
            System.err.print(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EvolutionControl().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(EvolutionControl.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StartBut;
    private javax.swing.JLabel PopSizeText;
    private javax.swing.JLabel IterStepText;
    private DataVis data_vis;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField popsize;
    private javax.swing.JTextField iterstep;
    // End of variables declaration//GEN-END:variables
}
